# Generated by Django 3.1.7 on 2021-02-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starseed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='equity',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='person',
            field=models.CharField(default='', max_length=255),
        ),
    ]
