# Generated by Django 3.1.7 on 2021-03-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starseed', '0002_auto_20210227_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='email2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
