# Generated by Django 3.2.7 on 2021-09-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starseed', '0005_auto_20210302_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='captcha',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='equity',
            field=models.IntegerField(default='', max_length=255),
        ),
    ]
